version: "3.9"
services:

  mqtt_mosquitto_broker:
    image: mjenz/rpi-mosquitto:1.4.15
    hostname: mqtt_mosquitto_broker
    container_name: mqtt_mosquitto_broker
    restart: always
    expose:
      - "1883"
    ports:
      - "1883:1883"

  mongo:
    image: mongo:4.4.2-bionic
    hostname: mongo
    container_name: mongo
    restart: always
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u admin -p mongo_admin_iot --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - "27017-27019:27017-27019"
    environment:
      MONGO_INITDB_DATABASE: "iot_db"
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "mongo_admin_iot"
    volumes:
      - ./docker/MongoDb/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - /media/dankers-iot/iot-drive/mongo-volume:/data/db

  mongo-express:
    image: mongo-express:0.54.0
    hostname: mongo-express
    container_name: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo_admin_iot

  home-automation-framework:
    image: dankersw/home_automation_framework:v1.0.2
    hostname: framework
    container_name: framework
    restart: always
    depends_on:
      - mongo
      - mqtt_mosquitto_broker

  backend:
    image: dankersw/home-automation-backend:v1.2.3
    hostname: backend
    container_name: backend
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
  
  frontend:
    image: dankersw/home-automation-frontend:v1.1.4
    hostname: frontend
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend 

volumes:
  mongo-volume:
